.PHONY: clean All

All:
	@echo "----------Building project:[ Accounts - Debug ]----------"
	@cd "Accounts" && "$(MAKE)" -f  "Accounts.mk"
clean:
	@echo "----------Cleaning project:[ Accounts - Debug ]----------"
	@cd "Accounts" && "$(MAKE)" -f  "Accounts.mk" clean
