.PHONY: clean All

All:
	@echo "----------Building project:[ 15_SectionChallenge - Debug ]----------"
	@cd "15_SectionChallenge" && "$(MAKE)" -f  "15_SectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ 15_SectionChallenge - Debug ]----------"
	@cd "15_SectionChallenge" && "$(MAKE)" -f  "15_SectionChallenge.mk" clean
