.PHONY: clean All

All:
	@echo "----------Building project:[ 12_LogicalOperators - Debug ]----------"
	@cd "12_LogicalOperators" && "$(MAKE)" -f  "12_LogicalOperators.mk"
clean:
	@echo "----------Cleaning project:[ 12_LogicalOperators - Debug ]----------"
	@cd "12_LogicalOperators" && "$(MAKE)" -f  "12_LogicalOperators.mk" clean
