.PHONY: clean All

All:
	@echo "----------Building project:[ 07_Vectors - Debug ]----------"
	@cd "07_Vectors" && "$(MAKE)" -f  "07_Vectors.mk"
clean:
	@echo "----------Cleaning project:[ 07_Vectors - Debug ]----------"
	@cd "07_Vectors" && "$(MAKE)" -f  "07_Vectors.mk" clean
