.PHONY: clean All

All:
	@echo "----------Building project:[ 20_CppStrings - Debug ]----------"
	@cd "20_CppStrings" && "$(MAKE)" -f  "20_CppStrings.mk"
clean:
	@echo "----------Cleaning project:[ 20_CppStrings - Debug ]----------"
	@cd "20_CppStrings" && "$(MAKE)" -f  "20_CppStrings.mk" clean
