.PHONY: clean All

All:
	@echo "----------Building project:[ Refresher - Debug ]----------"
	@cd "Refresher" && "$(MAKE)" -f  "Refresher.mk"
clean:
	@echo "----------Cleaning project:[ Refresher - Debug ]----------"
	@cd "Refresher" && "$(MAKE)" -f  "Refresher.mk" clean
