.PHONY: clean All

All:
	@echo "----------Building project:[ 11_StringStreams - Debug ]----------"
	@cd "11_StringStreams" && "$(MAKE)" -f  "11_StringStreams.mk"
clean:
	@echo "----------Cleaning project:[ 11_StringStreams - Debug ]----------"
	@cd "11_StringStreams" && "$(MAKE)" -f  "11_StringStreams.mk" clean
