.PHONY: clean All

All:
	@echo "----------Building project:[ 03_MoveConstructors - Debug ]----------"
	@cd "03_MoveConstructors" && "$(MAKE)" -f  "03_MoveConstructors.mk"
clean:
	@echo "----------Cleaning project:[ 03_MoveConstructors - Debug ]----------"
	@cd "03_MoveConstructors" && "$(MAKE)" -f  "03_MoveConstructors.mk" clean
