.PHONY: clean All

All:
	@echo "----------Building project:[ 08_SectionChallenge - Debug ]----------"
	@cd "08_SectionChallenge" && "$(MAKE)" -f  "08_SectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ 08_SectionChallenge - Debug ]----------"
	@cd "08_SectionChallenge" && "$(MAKE)" -f  "08_SectionChallenge.mk" clean
