.PHONY: clean All

All:
	@echo "----------Building project:[ 11_PassingArgumentsToBaseConstructors - Debug ]----------"
	@cd "11_PassingArgumentsToBaseConstructors" && "$(MAKE)" -f  "11_PassingArgumentsToBaseConstructors.mk"
clean:
	@echo "----------Cleaning project:[ 11_PassingArgumentsToBaseConstructors - Debug ]----------"
	@cd "11_PassingArgumentsToBaseConstructors" && "$(MAKE)" -f  "11_PassingArgumentsToBaseConstructors.mk" clean
