.PHONY: clean All

All:
	@echo "----------Building project:[ Ascii - Debug ]----------"
	@cd "Ascii" && "$(MAKE)" -f  "Ascii.mk"
clean:
	@echo "----------Cleaning project:[ Ascii - Debug ]----------"
	@cd "Ascii" && "$(MAKE)" -f  "Ascii.mk" clean
