.PHONY: clean All

All:
	@echo "----------Building project:[ 03_OperatorOverloadingMove - Debug ]----------"
	@cd "03_OperatorOverloadingMove" && "$(MAKE)" -f  "03_OperatorOverloadingMove.mk"
clean:
	@echo "----------Cleaning project:[ 03_OperatorOverloadingMove - Debug ]----------"
	@cd "03_OperatorOverloadingMove" && "$(MAKE)" -f  "03_OperatorOverloadingMove.mk" clean
