.PHONY: clean All

All:
	@echo "----------Building project:[ 18_ContainerAdaptorsPriorityQueue - Debug ]----------"
	@cd "18_ContainerAdaptorsPriorityQueue" && "$(MAKE)" -f  "18_ContainerAdaptorsPriorityQueue.mk"
clean:
	@echo "----------Cleaning project:[ 18_ContainerAdaptorsPriorityQueue - Debug ]----------"
	@cd "18_ContainerAdaptorsPriorityQueue" && "$(MAKE)" -f  "18_ContainerAdaptorsPriorityQueue.mk" clean
