.PHONY: clean All

All:
	@echo "----------Building project:[ 15_AssociativeContainersMap - Debug ]----------"
	@cd "15_AssociativeContainersMap" && "$(MAKE)" -f  "15_AssociativeContainersMap.mk"
clean:
	@echo "----------Cleaning project:[ 15_AssociativeContainersMap - Debug ]----------"
	@cd "15_AssociativeContainersMap" && "$(MAKE)" -f  "15_AssociativeContainersMap.mk" clean
