.PHONY: clean All

All:
	@echo "----------Building project:[ 08_IntroToSTLAlgorithms - Debug ]----------"
	@cd "08_IntroToSTLAlgorithms" && "$(MAKE)" -f  "08_IntroToSTLAlgorithms.mk"
clean:
	@echo "----------Cleaning project:[ 08_IntroToSTLAlgorithms - Debug ]----------"
	@cd "08_IntroToSTLAlgorithms" && "$(MAKE)" -f  "08_IntroToSTLAlgorithms.mk" clean
