.PHONY: clean All

All:
	@echo "----------Building project:[ PointerRefresher - Debug ]----------"
	@cd "PointerRefresher" && "$(MAKE)" -f  "PointerRefresher.mk"
clean:
	@echo "----------Cleaning project:[ PointerRefresher - Debug ]----------"
	@cd "PointerRefresher" && "$(MAKE)" -f  "PointerRefresher.mk" clean
