.PHONY: clean All

All:
	@echo "----------Building project:[ 07_UnscopedEnumeration - Debug ]----------"
	@cd "07_UnscopedEnumeration" && "$(MAKE)" -f  "07_UnscopedEnumeration.mk"
clean:
	@echo "----------Cleaning project:[ 07_UnscopedEnumeration - Debug ]----------"
	@cd "07_UnscopedEnumeration" && "$(MAKE)" -f  "07_UnscopedEnumeration.mk" clean
