.PHONY: clean All

All:
	@echo "----------Building project:[ 24_OOPClassesAndObjects - Debug ]----------"
	@cd "24_OOPClassesAndObjects" && "$(MAKE)" -f  "24_OOPClassesAndObjects.mk"
clean:
	@echo "----------Cleaning project:[ 24_OOPClassesAndObjects - Debug ]----------"
	@cd "24_OOPClassesAndObjects" && "$(MAKE)" -f  "24_OOPClassesAndObjects.mk" clean
